### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by vdrandom** [9seconds/mtg#188]
v2.0 randomly crashes. I run it on archlinux, built from aur. Debug log does not point to any reason, and I don't really see any way to reproduce it, it just happens every few hours.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x719ee6]
goroutine 14629 [running]:
github.com/9seconds/mtg/v2/mtglib/internal/relay.(*Relay).transmit.func1(0x7fc275926328, 0xc000251320, 0x7fc275926350, 0xc000251350, 0xc0002f4f10, 0xc0002dc180)
        github.com/9seconds/mtg/v2/mtglib/internal/relay/relay.go:75 +0x66
github.com/9seconds/mtg/v2/mtglib/internal/relay.(*Relay).transmit(0xc0002dc180, 0x7fc275926328, 0xc000251320, 0x7fc275926350, 0xc000251350, 0xc00035a000, 0x4000, 0x4000, 0xa3199e, 0x4, ...)
        github.com/9seconds/mtg/v2/mtglib/internal/relay/relay.go:92 +0x205
created by github.com/9seconds/mtg/v2/mtglib/internal/relay.(*Relay).Process
        github.com/9seconds/mtg/v2/mtglib/internal/relay/relay.go:55 +0x3b6
mtg@default.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by 9seconds** [comment]
Seems like a race condition in a place I thought I've fixed long time ago. Apparently I see no crashes but it could be I'm just lucky. I'll try to rewrite this part of code because it looks quite fragile, and such simple thing cause so many errors. Thanks. I hope to make a fix ASAP.

**Comment by 9seconds** [comment]
I hope my analysis is correct and #189 will solve the issue.
